<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
        <MacroDeckSdkVersion Condition="'$(MacroDeckSdkVersion)' == ''">3.0.0-*</MacroDeckSdkVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="MacroDeck.Localization" Version="$(MacroDeckSdkVersion)" />
        <PackageVersion Include="MacroDeck.Plugin.Analyzers" Version="$(MacroDeckSdkVersion)" />
        <PackageVersion Include="MacroDeck.Plugin.Hosting" Version="$(MacroDeckSdkVersion)" />
        <PackageVersion Include="MacroDeck.Plugin.Serilog" Version="$(MacroDeckSdkVersion)" />
        <PackageVersion Include="MacroDeck.Sdk" Version="$(MacroDeckSdkVersion)" />
        <PackageVersion Include="NAudio" Version="2.2.1" />
    </ItemGroup>
</Project>
