<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <WarningsAsErrors>CS8602</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Company>CJHackerYT</Company>
        <Authors>CJHackerYT</Authors>
        <Product>SoundBox</Product>
        <Description>A Windows soundboard plugin for Macro Deck 3.</Description>
        <Version>0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MacroDeck.Plugin.Analyzers" PrivateAssets="all" />
        <PackageReference Include="MacroDeck.Localization" />
        <PackageReference Include="MacroDeck.Plugin.Hosting" />
        <PackageReference Include="MacroDeck.Plugin.Serilog" />
        <PackageReference Include="MacroDeck.Sdk" />
        <PackageReference Include="NAudio" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="Assets\icon.svg" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="macrodeck-build.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
